# Generated by Django 4.1 on 2022-09-02 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("x", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_id", models.CharField(max_length=100)),
                ("player", models.CharField(max_length=100)),
                ("birth_year", models.CharField(blank=True, max_length=100, null=True)),
                ("hof", models.BooleanField(default=False)),
                ("num_seasons", models.IntegerField()),
                ("first_seas", models.IntegerField()),
                ("last_seas", models.IntegerField()),
                (
                    "img_url",
                    models.TextField(
                        default="https://cdn.nba.com/manage/2021/07/NBA_75-690x588.jpg"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Stat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seas_id", models.CharField(blank=True, max_length=100, null=True)),
                ("season", models.CharField(blank=True, max_length=100, null=True)),
                ("pos", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("experience", models.CharField(blank=True, max_length=100, null=True)),
                ("lg", models.CharField(blank=True, max_length=100, null=True)),
                ("tm", models.CharField(blank=True, max_length=100, null=True)),
                ("g", models.CharField(blank=True, max_length=100, null=True)),
                ("gs", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "mp_per_game",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "fg_per_game",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "fga_per_game",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("fg_percent", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "x3p_per_game",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "x3pa_per_game",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "x3p_percent",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "x2p_per_game",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "x2pa_per_game",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "x2p_percent",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "e_fg_percent",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "ft_per_game",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "fta_per_game",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ft_percent", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "orb_per_game",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "drb_per_game",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "trb_per_game",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "ast_per_game",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "stl_per_game",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "blk_per_game",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "tov_per_game",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "pf_per_game",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "pts_per_game",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("per", models.CharField(blank=True, max_length=100, null=True)),
                ("ts_percent", models.CharField(blank=True, max_length=100, null=True)),
                ("x3p_ar", models.CharField(blank=True, max_length=100, null=True)),
                ("f_tr", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "orb_percent",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "drb_percent",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "trb_percent",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "ast_percent",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "stl_percent",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "blk_percent",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "tov_percent",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "usg_percent",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ows", models.CharField(blank=True, max_length=100, null=True)),
                ("dws", models.CharField(blank=True, max_length=100, null=True)),
                ("ws", models.CharField(blank=True, max_length=100, null=True)),
                ("ws_48", models.CharField(blank=True, max_length=100, null=True)),
                ("obpm", models.CharField(blank=True, max_length=100, null=True)),
                ("dbpm", models.CharField(blank=True, max_length=100, null=True)),
                ("bpm", models.CharField(blank=True, max_length=100, null=True)),
                ("vorp", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="nba.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField()),
                (
                    "chart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="nba.chart",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="nba.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(default=" ")),
                (
                    "chart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="nba.chart",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="nba.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chart",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="charts",
                to="nba.user",
            ),
        ),
        migrations.AddField(
            model_name="chart",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="charts",
                to="nba.player",
            ),
        ),
    ]
