# Generated by Django 4.1 on 2022-09-01 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_id", models.CharField(max_length=100)),
                ("player", models.CharField(max_length=100)),
                ("birth_year", models.IntegerField()),
                ("num_seasons", models.IntegerField()),
                ("first_seas", models.IntegerField()),
                ("last_seas", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Stat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seas_id", models.FloatField()),
                ("season", models.FloatField()),
                ("pos", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("experience", models.FloatField()),
                ("lg", models.FloatField()),
                ("tm", models.FloatField()),
                ("g", models.FloatField()),
                ("gs", models.FloatField()),
                ("mp_per_game", models.FloatField()),
                ("fg_per_game", models.FloatField()),
                ("fga_per_game", models.FloatField()),
                ("fg_percent", models.FloatField()),
                ("x3p_per_game", models.FloatField()),
                ("x3pa_per_game", models.FloatField()),
                ("x3p_percent", models.FloatField()),
                ("x2p_per_game", models.FloatField()),
                ("x2pa_per_game", models.FloatField()),
                ("x2p_percent", models.FloatField()),
                ("e_fg_percent", models.FloatField()),
                ("ft_per_game", models.FloatField()),
                ("fta_per_game", models.FloatField()),
                ("ft_percent", models.FloatField()),
                ("orb_per_game", models.FloatField()),
                ("drb_per_game", models.FloatField()),
                ("trb_per_game", models.FloatField()),
                ("ast_per_game", models.FloatField()),
                ("stl_per_game", models.FloatField()),
                ("blk_per_game", models.FloatField()),
                ("tov_per_game", models.FloatField()),
                ("pf_per_game", models.FloatField()),
                ("pts_per_game", models.FloatField()),
                ("per", models.FloatField()),
                ("ts_percent", models.FloatField()),
                ("x3p_ar", models.FloatField()),
                ("f_tr", models.FloatField()),
                ("orb_percent", models.FloatField()),
                ("drb_percent", models.FloatField()),
                ("trb_percent", models.FloatField()),
                ("ast_percent", models.FloatField()),
                ("stl_percent", models.FloatField()),
                ("blk_percent", models.FloatField()),
                ("tov_percent", models.FloatField()),
                ("usg_percent", models.FloatField()),
                ("ows", models.FloatField()),
                ("dws", models.FloatField()),
                ("ws", models.FloatField()),
                ("ws_48", models.FloatField()),
                ("obpm", models.FloatField()),
                ("dbpm", models.FloatField()),
                ("bpm", models.FloatField()),
                ("vorp", models.FloatField()),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="nba.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("x", models.CharField(max_length=100)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charts",
                        to="nba.user",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charts",
                        to="nba.player",
                    ),
                ),
            ],
        ),
    ]
