# Generated by Django 4.1 on 2022-09-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nba", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chart", name="y_year", field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="age",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
