# Generated by Django 4.1.1 on 2022-09-09 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nba", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stat",
            old_name="Defensive_Rebounds_game",
            new_name="Defensive_Rebounds_per_game",
        ),
        migrations.RenameField(
            model_name="stat",
            old_name="Offensive_Rebounds_game",
            new_name="Offensive_Rebounds_per_game",
        ),
        migrations.RenameField(
            model_name="stat",
            old_name="x2_Point_Field_Goals_percent",
            new_name="x2_Point_Field_Goal_percent",
        ),
        migrations.RenameField(
            model_name="stat",
            old_name="x3_Point_Field_Goals_percent",
            new_name="x3_Point_Field_Goal_percent",
        ),
    ]
