# Generated by Django 4.1.1 on 2022-09-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "nba",
            "0002_rename_defensive_rebounds_game_stat_defensive_rebounds_per_game_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="chart", name="description", field=models.TextField(default=" "),
        ),
    ]
