# Generated by Django 4.1 on 2022-09-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nba", "0002_chart_y_year_alter_stat_age"),
    ]

    operations = [
        migrations.RemoveField(model_name="chart", name="player",),
        migrations.AddField(
            model_name="chart",
            name="player",
            field=models.ManyToManyField(to="nba.player"),
        ),
    ]
