# Generated by Django 4.1 on 2022-09-01 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nba", "0002_comment"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="count",),
        migrations.AddField(
            model_name="comment", name="text", field=models.TextField(default=" "),
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField()),
                (
                    "chart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="nba.chart",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="nba.user",
                    ),
                ),
            ],
        ),
    ]
