# Generated by Django 4.1 on 2022-09-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nba", "0003_remove_comment_count_comment_text_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="player", name="hof", field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="img_url",
            field=models.TextField(
                default="https://cdn.nba.com/manage/2021/07/NBA_75-690x588.jpg"
            ),
        ),
    ]
