# Generated by Django 4.1 on 2022-09-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nba", "0003_remove_chart_player_chart_player"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="player_id",
            field=models.CharField(max_length=1000000),
        ),
    ]
