# Generated by Django 4.1 on 2022-09-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nba", "0004_player_hof_player_img_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="birth_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
