# Generated by Django 4.1 on 2022-09-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nba", "0004_alter_player_player_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player", name="player_id", field=models.IntegerField(),
        ),
    ]
