# Generated by Django 4.1 on 2022-09-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nba", "0005_alter_player_birth_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="birth_year",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
