# Generated by Django 4.1 on 2022-09-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nba", "0006_alter_stat_vorp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stat",
            name="vorp",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
