# Generated by Django 4.1 on 2022-09-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nba", "0006_alter_player_birth_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stat",
            name="ast_per_game",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="ast_percent",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="blk_per_game",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="blk_percent",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="bpm",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="dbpm",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="drb_per_game",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="drb_percent",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="dws",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="e_fg_percent",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="experience",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="f_tr",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="fg_per_game",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="fg_percent",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="fga_per_game",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="ft_per_game",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="ft_percent",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="fta_per_game",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat", name="g", field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="gs",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat", name="lg", field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="stat",
            name="mp_per_game",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="obpm",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="orb_per_game",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="orb_percent",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="ows",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="per",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="pf_per_game",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="pts_per_game",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="seas_id",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="season",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="stl_per_game",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="stl_percent",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat", name="tm", field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="stat",
            name="tov_per_game",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="tov_percent",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="trb_per_game",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="trb_percent",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="ts_percent",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="usg_percent",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="vorp",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="ws",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="ws_48",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="x2p_per_game",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="x2p_percent",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="x2pa_per_game",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="x3p_ar",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="x3p_per_game",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="x3p_percent",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="x3pa_per_game",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
