# Generated by Django 4.1 on 2022-09-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nba", "0007_alter_stat_ast_per_game_alter_stat_ast_percent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stat",
            name="lg",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="stat",
            name="tm",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
