# Generated by Django 4.1 on 2022-09-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nba", "0008_rename_player_id_player_player_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chart",
            name="player",
            field=models.ManyToManyField(related_name="charts", to="nba.player"),
        ),
    ]
