# Generated by Django 4.1 on 2022-09-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nba", "0009_alter_chart_player"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stat",
            name="vorp",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
