# Generated by Django 4.1 on 2022-09-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nba", "0010_alter_stat_vorp"),
    ]

    operations = [
        migrations.RemoveField(model_name="player", name="id",),
        migrations.AlterField(
            model_name="player",
            name="player_number",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
