# Generated by Django 4.1 on 2022-09-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nba", "0011_remove_player_id_alter_player_player_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like", name="count", field=models.IntegerField(default=0),
        ),
    ]
