# Generated by Django 4.1 on 2022-09-06 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nba", "0013_user_pfp_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="chart",
            name="date",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
