# Generated by Django 4.1 on 2022-09-07 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nba", "0019_alter_chart_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chart",
            name="date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
