# Generated by Django 4.1 on 2022-09-09 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nba", "0020_alter_chart_date"),
    ]

    operations = [
        migrations.RenameField(model_name="stat", old_name="age", new_name="Age",),
        migrations.RenameField(
            model_name="stat", old_name="ast_per_game", new_name="Assists_per_game",
        ),
        migrations.RenameField(
            model_name="stat", old_name="ast_percent", new_name="Assists_percent",
        ),
        migrations.RenameField(
            model_name="stat", old_name="blk_per_game", new_name="Blocks_per_game",
        ),
        migrations.RenameField(
            model_name="stat", old_name="blk_percent", new_name="Blocks_percent",
        ),
        migrations.RenameField(
            model_name="stat", old_name="bpm", new_name="Box_Plus_Minus",
        ),
        migrations.RenameField(
            model_name="stat", old_name="dbpm", new_name="Defensive_Box_Plus_Minus",
        ),
        migrations.RenameField(
            model_name="stat",
            old_name="drb_per_game",
            new_name="Defensive_Rebounds_game",
        ),
        migrations.RenameField(
            model_name="stat",
            old_name="drb_percent",
            new_name="Defensive_Rebounds_percent",
        ),
        migrations.RenameField(
            model_name="stat", old_name="dws", new_name="Defensive_Win_Shares",
        ),
        migrations.RenameField(
            model_name="stat",
            old_name="e_fg_percent",
            new_name="Effective_Field_Goal_percent",
        ),
        migrations.RenameField(
            model_name="stat", old_name="experience", new_name="Experience",
        ),
        migrations.RenameField(
            model_name="stat", old_name="f_tr", new_name="Field_Goal_Attempts_per_game",
        ),
        migrations.RenameField(
            model_name="stat", old_name="fg_percent", new_name="Field_Goal_percent",
        ),
        migrations.RenameField(
            model_name="stat",
            old_name="fga_per_game",
            new_name="Free_Throw_Attempt_Rate",
        ),
        migrations.RenameField(
            model_name="stat",
            old_name="ft_per_game",
            new_name="Free_Throw_Attempts_per_game",
        ),
        migrations.RenameField(
            model_name="stat", old_name="ft_percent", new_name="Free_Throw_percent",
        ),
        migrations.RenameField(
            model_name="stat", old_name="fta_per_game", new_name="Free_Throws_per_game",
        ),
        migrations.RenameField(model_name="stat", old_name="g", new_name="Games",),
        migrations.RenameField(
            model_name="stat", old_name="gs", new_name="Games_started",
        ),
        migrations.RenameField(model_name="stat", old_name="lg", new_name="League",),
        migrations.RenameField(
            model_name="stat",
            old_name="mp_per_game",
            new_name="Minutes_Played_Per_Game",
        ),
        migrations.RenameField(
            model_name="stat", old_name="obpm", new_name="Offensive_Box_Plus_Minus",
        ),
        migrations.RenameField(
            model_name="stat",
            old_name="orb_per_game",
            new_name="Offensive_Rebounds_game",
        ),
        migrations.RenameField(
            model_name="stat",
            old_name="orb_percent",
            new_name="Offensive_Rebounds_percent",
        ),
        migrations.RenameField(
            model_name="stat", old_name="ows", new_name="Offensive_Win_Shares",
        ),
        migrations.RenameField(
            model_name="stat", old_name="per", new_name="Personal_Fouls_per_game",
        ),
        migrations.RenameField(
            model_name="stat",
            old_name="pf_per_game",
            new_name="Player_Efficiency_Rating",
        ),
        migrations.RenameField(
            model_name="stat", old_name="pts_per_game", new_name="Points_per_game",
        ),
        migrations.RenameField(model_name="stat", old_name="pos", new_name="Position",),
        migrations.RenameField(
            model_name="stat", old_name="seas_id", new_name="Seas_id",
        ),
        migrations.RenameField(
            model_name="stat", old_name="season", new_name="Season",
        ),
        migrations.RenameField(
            model_name="stat", old_name="stl_per_game", new_name="Steals_per_game",
        ),
        migrations.RenameField(
            model_name="stat", old_name="stl_percent", new_name="Steals_percent",
        ),
        migrations.RenameField(model_name="stat", old_name="tm", new_name="Team",),
        migrations.RenameField(
            model_name="stat",
            old_name="tov_per_game",
            new_name="Total_Rebounds_per_game",
        ),
        migrations.RenameField(
            model_name="stat",
            old_name="tov_percent",
            new_name="Total_Rebounds_percent",
        ),
        migrations.RenameField(
            model_name="stat",
            old_name="trb_per_game",
            new_name="True_Shooting_percent",
        ),
        migrations.RenameField(
            model_name="stat", old_name="trb_percent", new_name="Turnovers_per_game",
        ),
        migrations.RenameField(
            model_name="stat", old_name="ts_percent", new_name="Turnovers_percent",
        ),
        migrations.RenameField(
            model_name="stat", old_name="usg_percent", new_name="Usage_percent",
        ),
        migrations.RenameField(model_name="stat", old_name="vorp", new_name="VORP",),
        migrations.RenameField(
            model_name="stat", old_name="ws", new_name="Win_Shares",
        ),
        migrations.RenameField(
            model_name="stat", old_name="ws_48", new_name="Win_Shares_Per_48_Minutes",
        ),
        migrations.RenameField(
            model_name="stat",
            old_name="x2p_per_game",
            new_name="x2_Point_Field_Goal_Attempts_per_game",
        ),
        migrations.RenameField(
            model_name="stat",
            old_name="x2p_percent",
            new_name="x2_Point_Field_Goals_per_game",
        ),
        migrations.RenameField(
            model_name="stat",
            old_name="x2pa_per_game",
            new_name="x2_Point_Field_Goals_percent",
        ),
        migrations.RenameField(
            model_name="stat", old_name="x3p_ar", new_name="x3_Point_Attempt_Rate",
        ),
        migrations.RenameField(
            model_name="stat",
            old_name="x3p_per_game",
            new_name="x3_Point_Field_Goal_Attempts_per_game",
        ),
        migrations.RenameField(
            model_name="stat",
            old_name="x3p_percent",
            new_name="x3_Point_Field_Goals_per_game",
        ),
        migrations.RenameField(
            model_name="stat",
            old_name="x3pa_per_game",
            new_name="x3_Point_Field_Goals_percent",
        ),
    ]
