# Generated by Django 4.1 on 2022-09-09 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nba", "0021_rename_age_stat_age_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stat",
            old_name="Games_started",
            new_name="Field_Goals_per_game",
        ),
        migrations.RenameField(
            model_name="stat", old_name="fg_per_game", new_name="Games_Started",
        ),
    ]
